/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as charitySol from "./Charity.sol";
export type { charitySol };
export type { DAO } from "./DAO";
export type { DexAdapter } from "./DexAdapter";
export type { ERC20 } from "./ERC20";
export type { Foundation } from "./Foundation";
export type { FundManager } from "./FundManager";
export type { MyERC721 } from "./MyERC721";
export type { Staking } from "./Staking";
export type { Vesting } from "./Vesting";
