/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as charitySol from "./Charity.sol";
export type { charitySol };
export type { ERC20 } from "./ERC20";
export type { Foundation } from "./Foundation";
export type { FundManager } from "./FundManager";
