/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  HelloWorldContract,
  HelloWorldContractInterface,
} from "../../contracts/HelloWorldContract";

const _abi = [
  {
    inputs: [],
    name: "getNumber",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "helloWorld",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "number",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "_number",
        type: "int256",
      },
    ],
    name: "setNumber",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061033b806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80638381f58a146100515780639cf27f371461006f578063c605f76c1461008b578063f2c9ecd8146100a9575b600080fd5b6100596100c7565b60405161006691906101da565b60405180910390f35b61008960048036038101906100849190610226565b6100cd565b005b6100936100ff565b6040516100a091906102e3565b60405180910390f35b6100b1610178565b6040516100be91906101da565b60405180910390f35b60005481565b6100e1672750a159ec5df44160c01b6101be565b6100f5673a38a867333dac9160c01b6101be565b8060008190555050565b6060610115674d378a524a17d1ca60c01b6101be565b6101296780e0fb4eb3ceabbd60c01b6101be565b61013d67925ee48bd3721d8060c01b6101be565b6040518060400160405280601081526020017f48656c6c6f2c20457468657265756d2100000000000000000000000000000000815250905090565b600061018e67f9880d61633526b660c01b6101be565b6101a2670481c8d8a0727bd560c01b6101be565b6101b667eced3f9fb19f80f660c01b6101be565b600054905090565b50565b6000819050919050565b6101d4816101c1565b82525050565b60006020820190506101ef60008301846101cb565b92915050565b600080fd5b610203816101c1565b811461020e57600080fd5b50565b600081359050610220816101fa565b92915050565b60006020828403121561023c5761023b6101f5565b5b600061024a84828501610211565b91505092915050565b600081519050919050565b600082825260208201905092915050565b60005b8381101561028d578082015181840152602081019050610272565b60008484015250505050565b6000601f19601f8301169050919050565b60006102b582610253565b6102bf818561025e565b93506102cf81856020860161026f565b6102d881610299565b840191505092915050565b600060208201905081810360008301526102fd81846102aa565b90509291505056fea2646970667358221220b66160bad49040813c2b43c5174d2e9c90549a620ae555779e9b7ca862f9400664736f6c63430008120033";

type HelloWorldContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HelloWorldContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class HelloWorldContract__factory extends ContractFactory {
  constructor(...args: HelloWorldContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<HelloWorldContract> {
    return super.deploy(overrides || {}) as Promise<HelloWorldContract>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): HelloWorldContract {
    return super.attach(address) as HelloWorldContract;
  }
  override connect(signer: Signer): HelloWorldContract__factory {
    return super.connect(signer) as HelloWorldContract__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HelloWorldContractInterface {
    return new utils.Interface(_abi) as HelloWorldContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HelloWorldContract {
    return new Contract(address, _abi, signerOrProvider) as HelloWorldContract;
  }
}
