/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as charitySol from "./Charity.sol";
export { DAO__factory } from "./DAO__factory";
export { DexAdapter__factory } from "./DexAdapter__factory";
export { ERC20__factory } from "./ERC20__factory";
export { Foundation__factory } from "./Foundation__factory";
export { FundManager__factory } from "./FundManager__factory";
export { MyERC1155__factory } from "./MyERC1155__factory";
export { MyERC721__factory } from "./MyERC721__factory";
export { Staking__factory } from "./Staking__factory";
export { Vesting__factory } from "./Vesting__factory";
