/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as charitySol from "./Charity.sol";
export { Foundation__factory } from "./Foundation__factory";
export { FundManager__factory } from "./FundManager__factory";
